### ISSUE TITLE
encryption

### ISSUE THREAD

**Issue by iesrbt** [cvilsmeier/sqinn-go#5]
Hi there,
thanks for sqinn. Very good stuff!

Would it be possible for you to consider building a version that include database encryption on disk?
see: https://sqlite.org/com/see.html

and add support for key in: sq.Open()

(oh sorry, i guess it should go there: https://github.com/cvilsmeier/sqinn)

Cheers,
//JPG

**Comment by cvilsmeier** [comment]
Hi //JPG,
I have no plans to add SEE, as I'm not allowed to do so, because of licensing:
~~~
The core SQLite library is in the public domain. However, the extensions needed
to read and write an encrypted database file are licensed software. [...]
~~~
see https://www.sqlite.org/see/doc/trunk/www/readme.wiki

**Comment by iesrbt** [comment]
thanks for your answer!
indeed SEE is not a good fit.
what about: https://github.com/sqlcipher/sqlcipher
anyway.
